### ISSUE TITLE
Browsers compatibilities and click events issues

### ISSUE THREAD

**Issue by fquinio** [openmost/datalayer-sync#1]
Hello,

1. The method array.at() is not compatible with all browsers.
Instead, we had to use : 
`window._mtm.push(dataLayer[dataLayer.length-1]);`

2. With this synchronisation GTM => MTM, we loose in GTM the click event.
   We had to deactivate this synchronisation to keep all our GTM triggers and tags to work.

Fabrice Quinio

**Comment by ronan-hello** [comment]
Hi,

Thank you for this precious information.
Script have been updated right now.

Regards,
Ronan
